version: "2"
services:
  raid_bot:
    build: ./raid-bot
    image: webofneeds/raid_bot
    environment:
      - "api.serverUrl=${API_SERVER_URL}"
      - "api.username=${API_USERNAME}"
      - "api.password=${API_PASSWORD}"
      - "uri.node.default=${WON_NODE_BASE}/won/resource"
      - "won.node.uris=${WON_NODE_BASE}/won/resource"
      - "uri.prefix.owner=${WON_NODE_BASE}/raid_bot" # set this for the trust store alias
      - "raidbot.name=Pokemon Go Raid Bot"

      # keystore properties
      - "keystore.password"
      - "keystore.location=/usr/src/certs/keystore.jks"

      # truststore properties
      - "truststore.password"
      - "truststore.location=/usr/src/certs/truststore.jks"

      # mongodb config
      - "botContext.impl=mongoBotContext"
      - "botContext.mongodb.user=raid_bot"
      - "botContext.mongodb.pass=raid_bot"
      - "botContext.mongodb.host=mongodb"
      - "botContext.mongodb.port=27017"
      - "botContext.mongodb.database=raid_bot"
    depends_on:
      - mongodb
    volumes:
      - "certs:/usr/src/certs"

  mongodb:
    image: tutum/mongodb:3.2
    environment:
      - "MONGODB_USER=raid_bot"
      - "MONGODB_DATABASE=raid_bot"
      - "MONGODB_PASS=raid_bot"

volumes: certs:
